#cloud-config
hostname: @@{vm_name}@@

fqdn: @@{vm_name}@@.@@{domain}@@

users:
   - default
   - name: @@{linux.username}@@
     groups: sudo
     shell: /bin/bash
     lock_passwd: false
     ssh-authorized-keys:
      - @@{public key}@@
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]

chpasswd:
   list: |
     @@{linux.username}@@:@@{linux.secret}@@
   expire: false

runcmd:
   - nmcli connection migrate
   - nmcli con down "System eth0"
   - nmcli con del "System eth0"
   - nmcli con add con-name "System eth0" ifname eth0 type ethernet ip4 @@{vm_ip}@@/@@{subnet_mask_bits}@@ gw4 @@{gateway}@@ ipv4.dns "@@{dns1}@@ @@{dns2}@@"
   - nmcli con up "System eth0"
   - nmcli general reload
   - nmcli connection reload

packages:
  - git
  - wget
  - curl
  - unzip
  - tar
  - python3
  - cloud-guest-utils

package_upgrade: true

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

power_state:
  delay: "+1"
  mode: reboot
  message: Rebooting after cloud-init
  timeout: 30
  condition: True